language: cpp
branches: main

# before_script:
#   - mkdir -p build
#   - cd build
#   - rm -rf *
#   - cmake ..
dist: focal
script:
  - ./build.sh

after_script:
  - cd ..
  - git add .
  - git commit -m "travis auto build"
  - git push