language: cpp
branches: main
dist: focal

# before_script:
#   - mkdir -p build
#   - cd build
#   - rm -rf *
#   - cmake ..
script:
  - ./build.sh

after_script:
  - git add .
  - git commit -m "travis auto build"
  - git push